"""fix and recover email otps table

Revision ID: 53581556eb6f
Revises: a691777aaacb
Create Date: 2026-05-20 21:33:09.612642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53581556eb6f'
down_revision: Union[str, Sequence[str], None] = 'a691777aaacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "email_otps" not in inspector.get_table_names():
        op.create_table(
            "email_otps",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("email", sa.String(length=255), nullable=False),
            sa.Column("otp_code", sa.String(length=6), nullable=False),
            sa.Column("purpose", sa.String(length=50), nullable=False),
            sa.Column("is_used", sa.Boolean(), nullable=False, server_default=sa.false()),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    indexes = {index["name"] for index in inspector.get_indexes("email_otps")}
    if op.f("ix_email_otps_email") not in indexes:
        op.create_index(op.f("ix_email_otps_email"), "email_otps", ["email"], unique=False)
    if op.f("ix_email_otps_id") not in indexes:
        op.create_index(op.f("ix_email_otps_id"), "email_otps", ["id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###
