"""add_last_notification_sent_at_to_support_tickets

Revision ID: 784a91fb8a3b
Revises: add_last_online
Create Date: 2026-06-12 13:31:02.747169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '784a91fb8a3b'
down_revision: Union[str, Sequence[str], None] = 'add_last_online'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_embedding")
    bind = op.get_bind()
    support_ticket_columns = {c["name"] for c in inspect(bind).get_columns("support_tickets")}
    if "last_notification_sent_at" not in support_ticket_columns:
        op.add_column(
            "support_tickets",
            sa.Column("last_notification_sent_at", sa.DateTime(timezone=True), nullable=True),
        )
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               comment='Tuổi',
               existing_nullable=True)
    op.alter_column('users', 'last_online_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời gian hoạt động cuối cùng',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_online_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời gian hoạt động cuối cùng',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tuổi',
               existing_nullable=True)
    op.drop_column('support_tickets', 'last_notification_sent_at')
    op.create_index(op.f('ix_knowledge_chunks_embedding'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
