"""add bmi reminder settings

Revision ID: a1b2c3d4e5f6
Revises: f8a9b0c1d2e3
Create Date: 2026-06-24 08:11:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'f8a9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bmi_reminder_enabled', sa.Boolean(), nullable=True, server_default='false', comment='Bật/tắt nhắc nhở cập nhật BMI'))
    op.add_column('users', sa.Column('bmi_reminder_frequency', sa.String(length=20), nullable=True, server_default='weekly', comment='Tần suất nhắc nhở: daily, weekly'))
    op.add_column('users', sa.Column('last_notification_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Thời gian gửi thông báo cuối cùng'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_notification_sent_at')
    op.drop_column('users', 'bmi_reminder_frequency')
    op.drop_column('users', 'bmi_reminder_enabled')
    # ### end Alembic commands ###
