"""add wrist and ankle circumference fields

Revision ID: be0883201e23
Revises: d4e1f2a3b4c5
Create Date: 2026-06-03 16:42:35.556020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be0883201e23'
down_revision: Union[str, Sequence[str], None] = 'd4e1f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.add_column('bmi_records', sa.Column('wrist_circumference_cm', sa.Float(), nullable=True))
    op.add_column('bmi_records', sa.Column('ankle_circumference_cm', sa.Float(), nullable=True))
    op.add_column('bmi_records', sa.Column('wrist_to_height_ratio', sa.Float(), nullable=True))
    op.add_column('bmi_records', sa.Column('ankle_to_height_ratio', sa.Float(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               comment='Cân nặng (kg)',
               existing_nullable=True)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               comment='Chiều cao (cm)',
               existing_nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               comment='ID duy nhất của tài khoản Google',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Link ảnh đại diện của người dùng',
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Link ảnh đại diện của người dùng',
               existing_nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ID duy nhất của tài khoản Google',
               existing_nullable=True)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Chiều cao (cm)',
               existing_nullable=True)
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Cân nặng (kg)',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('bmi_records', 'ankle_to_height_ratio')
    op.drop_column('bmi_records', 'wrist_to_height_ratio')
    op.drop_column('bmi_records', 'ankle_circumference_cm')
    op.drop_column('bmi_records', 'wrist_circumference_cm')
    op.create_table('oauth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_tokens_pkey')),
    sa.UniqueConstraint('user_id', 'provider', name=op.f('uq_user_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_oauth_tokens_id'), 'oauth_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
